### ISSUE TITLE
Support language tags other than @de

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-ssg#24]
Today, I published the [Educational Subject Classification (ESC)](https://w3id.org/class/esc/) via SkoHub. Everything went fine regarding the process (pushing int eh GitHub master and updating SkoHub via webhook).

For labels to be shown, I had to replace `@en` tags by  de`, see https://github.com/acka47/skos/commit/b791afbd891e8e96fa9cccfdc6489ed71bf419e4

**Comment by literarymachine** [comment]
Our usage of JSON-LD language maps is reflected in the [GraphQL schema](https://github.com/hbz/skohub-ssg/blob/dafe1d6166a4a9ebc8779d57edc4a482e2306751/src/types.js) we use in Gatsby. This means that we have to list every single supported language as a valid property. We could get around this by not using language maps and simply allow any string as values for `@language`. This way, we would simply support any language tags. Otherwise we would need a list of languages. The [IANA Language Subtag Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) would probably be right source.

**Comment by literarymachine** [comment]
> For labels to be shown, I had to replace `@en` tags

Support for `@en` added in https://github.com/hbz/skohub-ssg/pull/28/commits/dafe1d6166a4a9ebc8779d57edc4a482e2306751.

**Comment by literarymachine** [comment]
@acka47 ae488bd adds support for all language tags.

**Comment by acka47** [comment]
+1 I tested it, and it works fine, see https://test.skohub.io/acka47/skos/w3id.org/class/esc/scheme.html.
