### ISSUE TITLE
Support scopeNotes with single quote

### ISSUE THREAD

**Issue by acka47** [hbz/skohub-ssg#25]
Today, I published the [Educational Subject Classification (ESC)](https://w3id.org/class/esc/) via SkoHub.
However, although this is also a slash URI vocab, the HTML rendering did not work out of the box. The first problem was the single quotes for `scopeNote`. When I replaced them with triple quotes (https://github.com/acka47/skos/commit/781c5422646dca60a13570fb15787b9709bfa9a1) it got a bit better, but no labels were shown. (I fixed this with only using `@de` language tags, see #24.)

**Comment by literarymachine** [comment]
I cannot replicate this, but whatever the issue is here, it most likely not the usage of single quotes. See this single quote version of the [ESC](https://github.com/literarymachine/skos/blob/master/esc.ttl) and its [build](https://test.skohub.io/literarymachine/skos/w3id.org/class/esc/scheme.html).

**Comment by literarymachine** [comment]
@acka47 closing this assuming that your build trouble was actually related to #24.
